### ISSUE TITLE
Create model with configuration YAML spec

### ISSUE THREAD

**Issue by HeavyWombat** [homeport/disrupt-o-meter#3]
Create a model file which contains structs for the YAML/JSON configuration of the tool.

In contrast to `uptimer`, we should support both absolute and relative thresholds.

Example:
```yaml
---
cf:
  domain: foobar.com
  api-endpoint: api.foobar.com
  skip-ssl-validation: true
  username: foo
  password: bar

tasks:
- cmd: /bin/bash
  args:
  - -c
  - |
    #!/bin/bash

    set -euo pipefail

    execute something | awesome

hurdles:
- name: app-pushability
  threshold: 2 %
- name: http-availability
  threshold: 5 %
- name: cf-log-functionality
  threshold: 4
- name: cf-recent-log-functionality
  threshold: 4
- name: syslog-functionality
  threshold: 10 %
```
